sonar.projectKey=cst-notification-service
sonar.projectName=Customer Support Ticketing - notification-service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8
