// Central action-type constants shared by actions and reducers.
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TICKETS_FETCH_START = 'TICKETS_FETCH_START';
export const TICKETS_FETCH_SUCCESS = 'TICKETS_FETCH_SUCCESS';
export const TICKETS_FETCH_FAILURE = 'TICKETS_FETCH_FAILURE';

export const DASHBOARD_FETCH_START = 'DASHBOARD_FETCH_START';
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD_FETCH_SUCCESS';
export const DASHBOARD_FETCH_FAILURE = 'DASHBOARD_FETCH_FAILURE';
